### ISSUE TITLE
Deny does not work with the entity "witherstormmod:wither_storm"

### ISSUE THREAD

**Issue by TzunamiDev** [Kotori316/LimitMobSpawn#14]
Deny does not work with the entity **"witherstormmod:wither_storm"** of the mod **"Cracker's Wither Storm Mod"**

Errors found in console or debug.log: **None**

How to replicate the problem:
1. Run comman `/limitmobspawn add deny entity[entity=witherstormmod:wither_storm]`
2. Spawn a WitherStorm as indicated in the mod information (as you would normally summon a wither but with a command block in between) "or" by command: `/summon witherstormmod:wither_storm`

Forge version: 47.2.20 (mc 1.20.1)
LimitMobSpawn mod version: LimitMobSpawn-20.1.0.jar
Cracker's Wither Storm Mod version: witherstormmod-1.20.1-4.0.1.1.jar

Server version: "arclight-1.20.1-1.0.5-1a8925b (Trials/1.0.5)"

**Comment by Kotori316** [comment]
It's indented.
I added some condition to check whether this mod should "modify" the spawning. One is that the entity is treated as "boss". `witherstormmod:wither_storm` looks like a boss, so this mod doesn't deny the spawn.

I found the logic seems not working in 1.20.1, so I'll add a way to bypass the boss check in next version for 1.20.1

**Comment by Kotori316** [comment]
Use 20.1.1
