### ISSUE TITLE
Open source licence

### ISSUE THREAD

**Issue by iTrooz** [Kotori316/LimitMobSpawn#16]
Hey ! I'd like to make some contributions to this mod in the future. Could you please choose an open source licence for the mod ?

You may want to check this: https://choosealicense.com/no-permission/

**Comment by Kotori316** [comment]
What kind of contribution? PR via GitHub?
Source code is MIT license, and assets and generated binary are All Right Reserved. I'll push license file later.

**Comment by iTrooz** [comment]
Thanks !
