### ISSUE TITLE
[question] Some of the example datapacks use forge tags, how does it differ from fabric?

### ISSUE THREAD

**Issue by netcore10** [Kotori316/LimitMobSpawn#4]
Namely, i want to deny spawns in a modded dimension, but doubt forge:dimension_loaded works in 1.18.2 fabric

**Comment by Kotori316** [comment]
See example in [fabric branch](https://github.com/Kotori316/LimitMobSpawn-fabric/tree/1.18-fabric/src/test/resources/data/limitmobspawn/limitmobspawn).

You don't have to fill condition block, so you can remove `condition` or `fabric:load_conditions` block if you don't need.
For more information, see the examples.

Forge provides only [these conditions](https://github.com/MinecraftForge/MinecraftForge/tree/1.18.x/src/main/java/net/minecraftforge/common/crafting/conditions). There isn't something related to dimension.
Fabric provides [these](https://github.com/FabricMC/fabric/blob/1.18.2/fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/api/resource/conditions/v1/DefaultResourceConditions.java).

**Comment by netcore10** [comment]
thanks very much!
